import 'package:flutter/material.dart';

/// Return IconData
class Ico {
  // This class is not meant to be instantiated or extended; this constructor
  // prevents instantiation and extension.
  static const _fontPackage = 'ico';
  Ico._();
// General Icons__________________________________________________________
  static const IconData add_filled =
      IconData(0xE900, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData add_outline =
      IconData(0xE901, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData adjust_filled =
      IconData(0xE902, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData adjust_outline =
      IconData(0xE903, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData alarm_filled =
      IconData(0xE904, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData alarm_outline =
      IconData(0xE905, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData apps_filled =
      IconData(0xE906, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData apps_outline =
      IconData(0xE907, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_down =
      IconData(0xE908, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_down_01 =
      IconData(0xE909, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_left =
      IconData(0xE90A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_left_01 =
      IconData(0xE90B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_right =
      IconData(0xE90C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_right_01 =
      IconData(0xE90D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_up =
      IconData(0xE90E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_up_01 =
      IconData(0xE90F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData attach =
      IconData(0xE910, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData at_sign =
      IconData(0xE911, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData at_sign_filled =
      IconData(0xE912, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData award_filled =
      IconData(0xE913, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData award_outline =
      IconData(0xE914, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData backspace_filled =
      IconData(0xE915, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData backspace_outline =
      IconData(0xE916, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bag_filled =
      IconData(0xE917, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bag_outline =
      IconData(0xE918, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bank_filled =
      IconData(0xE919, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bank_outline =
      IconData(0xE91A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData beakers_circle_filled =
      IconData(0xE91B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData beakers_circle_outline =
      IconData(0xE91C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData beakers_triangle_filled =
      IconData(0xE91D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData beakers_triangle_outline =
      IconData(0xE91E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bluetooth_outline =
      IconData(0xE91F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bookmark_filled =
      IconData(0xE920, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bookmark_outline =
      IconData(0xE921, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_check_filled =
      IconData(0xE922, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_check_outline =
      IconData(0xE923, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_filled =
      IconData(0xE924, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_mark_filled =
      IconData(0xE925, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_mark_outline =
      IconData(0xE926, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_open_filled =
      IconData(0xE927, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_open_outline =
      IconData(0xE928, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_outline =
      IconData(0xE929, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData box_filled =
      IconData(0xE92A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData box_outline =
      IconData(0xE92B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData calendar_filled =
      IconData(0xE92C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData calendar_outline =
      IconData(0xE92D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cancel_filled =
      IconData(0xE92E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cancel_outline =
      IconData(0xE92F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData card_filled =
      IconData(0xE930, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData card_outline =
      IconData(0xE931, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData chart_pie_alt_filled =
      IconData(0xE932, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData chart_pie_alt_outline =
      IconData(0xE933, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData chart_pie_filled =
      IconData(0xE934, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData chart_pie_outline =
      IconData(0xE935, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData check =
      IconData(0xE936, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData checked_box_filled =
      IconData(0xE937, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData checked_box_outline =
      IconData(0xE938, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clipboard_alt_filled =
      IconData(0xE939, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clipboard_alt_outline =
      IconData(0xE93A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clipboard_filled =
      IconData(0xE93B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clipboard_outline =
      IconData(0xE93C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clock_filled =
      IconData(0xE93D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clock_outline =
      IconData(0xE93E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_check_filled =
      IconData(0xE93F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_check_outline =
      IconData(0xE940, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_download_filled =
      IconData(0xE941, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_download_outline =
      IconData(0xE942, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_filled =
      IconData(0xE943, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_off_filled =
      IconData(0xE944, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_off_outline =
      IconData(0xE945, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_outline =
      IconData(0xE946, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_upload_filled =
      IconData(0xE947, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_upload_outline =
      IconData(0xE948, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData collapse =
      IconData(0xE949, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData columns_filled =
      IconData(0xE94A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData columns_outline =
      IconData(0xE94B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData copy_filled =
      IconData(0xE94C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData copy_outline =
      IconData(0xE94D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cross_outline =
      IconData(0xE94E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData current_location_filled =
      IconData(0xE94F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData current_location_outline =
      IconData(0xE950, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cursor_filled =
      IconData(0xE951, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cursor_outline =
      IconData(0xE952, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData delete_filled =
      IconData(0xE953, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData delete_forever_filled =
      IconData(0xE954, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData delete_forever_outline =
      IconData(0xE955, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData delete_outline =
      IconData(0xE956, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData diamond_filled =
      IconData(0xE957, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData diamond_outline =
      IconData(0xE958, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData download_01_filled =
      IconData(0xE959, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData download_01_outline =
      IconData(0xE95A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData download_filled =
      IconData(0xE95B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData download_outline =
      IconData(0xE95C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData edit_alt_filled =
      IconData(0xE95D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData edit_alt_outline =
      IconData(0xE95E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData edit_filled =
      IconData(0xE95F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData edit_outline =
      IconData(0xE960, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData exchange =
      IconData(0xE961, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData expand =
      IconData(0xE962, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData explore_filled =
      IconData(0xE963, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData explore_outline =
      IconData(0xE964, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData eye_closed_filled =
      IconData(0xE965, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData eye_closed_outline =
      IconData(0xE966, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData eye_filled =
      IconData(0xE967, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData eye_outline =
      IconData(0xE968, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_add_filled =
      IconData(0xE969, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_add_outline =
      IconData(0xE96A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_download_filled =
      IconData(0xE96B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_download_outline =
      IconData(0xE96C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_empty_filled =
      IconData(0xE96D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_empty_outline =
      IconData(0xE96E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_favourite_filled =
      IconData(0xE96F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_favourite_outline =
      IconData(0xE970, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_filled =
      IconData(0xE971, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_ftp_filled =
      IconData(0xE972, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_ftp_outline =
      IconData(0xE973, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_image_filled =
      IconData(0xE974, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_image_outline =
      IconData(0xE975, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_invalid_filled =
      IconData(0xE976, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_invalid_outline =
      IconData(0xE977, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_outline =
      IconData(0xE978, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_remove_filled =
      IconData(0xE979, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_remove_outline =
      IconData(0xE97A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_unknown_filled =
      IconData(0xE97B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_unknown_outline =
      IconData(0xE97C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_upload_filled =
      IconData(0xE97D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_upload_outline =
      IconData(0xE97E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_user_filled =
      IconData(0xE97F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_user_outline =
      IconData(0xE980, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData filter_filled =
      IconData(0xE981, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData filter_outline =
      IconData(0xE982, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData fire_filled =
      IconData(0xE983, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData fire_outline =
      IconData(0xE984, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_add_filled =
      IconData(0xE985, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_add_outline =
      IconData(0xE986, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_block_filled =
      IconData(0xE987, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_block_outline =
      IconData(0xE988, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_delete_filled =
      IconData(0xE989, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_delete_outline =
      IconData(0xE98A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_filled =
      IconData(0xE98B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_ftp_filled =
      IconData(0xE98C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_ftp_outline =
      IconData(0xE98D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_lock_filled =
      IconData(0xE98E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_lock_outline =
      IconData(0xE98F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_open_filled =
      IconData(0xE990, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_open_outline =
      IconData(0xE991, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_outline =
      IconData(0xE992, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_search_filled =
      IconData(0xE993, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_search_outline =
      IconData(0xE994, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_user_filled =
      IconData(0xE995, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_user_outline =
      IconData(0xE996, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData gift_filled =
      IconData(0xE997, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData gift_outline =
      IconData(0xE998, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData globe_filled =
      IconData(0xE999, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData globe_outline =
      IconData(0xE99A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData group =
      IconData(0xE99B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heartbeat_filled =
      IconData(0xE99C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heartbeat_outline =
      IconData(0xE99D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_add_filled =
      IconData(0xE99E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_add_outline =
      IconData(0xE99F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_filled =
      IconData(0xE9A0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_off_filled =
      IconData(0xE9A1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_off_outline =
      IconData(0xE9A2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_outline =
      IconData(0xE9A3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_remove_filled =
      IconData(0xE9A4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_remove_outline =
      IconData(0xE9A5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData history_outline =
      IconData(0xE9A6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData home_filled =
      IconData(0xE9A7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData home_outline =
      IconData(0xE9A8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData hotspot =
      IconData(0xE9A9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData image_filled =
      IconData(0xE9AA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData image_outline =
      IconData(0xE9AB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_circle_filled =
      IconData(0xE9AC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_circle_outline =
      IconData(0xE9AD, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_rect_filled =
      IconData(0xE9AE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_rect_outline =
      IconData(0xE9AF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_triangle_filled =
      IconData(0xE9B0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_triangle_outline =
      IconData(0xE9B1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData invoice_filled =
      IconData(0xE9B2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData invoice_outline =
      IconData(0xE9B3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData key_filled =
      IconData(0xE9B4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData key_outline =
      IconData(0xE9B5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData layout_filled =
      IconData(0xE9B6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData layout_outline =
      IconData(0xE9B7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_alt_filled =
      IconData(0xE9B8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_alt_outline =
      IconData(0xE9B9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_filled =
      IconData(0xE9BA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_off_filled =
      IconData(0xE9BB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_off_outline =
      IconData(0xE9BC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_outline =
      IconData(0xE9BD, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightning_alt_filled =
      IconData(0xE9BE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightning_alt_outline =
      IconData(0xE9BF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightning_filled =
      IconData(0xE9C0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightning_outline =
      IconData(0xE9C1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_add_outline =
      IconData(0xE9C2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_check_filled =
      IconData(0xE9C3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_check_outline =
      IconData(0xE9C4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_filled =
      IconData(0xE9C5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_outline =
      IconData(0xE9C6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_plus_filled =
      IconData(0xE9C7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_question_filled =
      IconData(0xE9C8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_question_outline =
      IconData(0xE9C9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lock_filled =
      IconData(0xE9CA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lock_outline =
      IconData(0xE9CB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lock_time_filled =
      IconData(0xE9CC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lock_time_outline =
      IconData(0xE9CD, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData login_filled_1 =
      IconData(0xE9CE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData login_filled =
      IconData(0xE9CF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData login_outline_1 =
      IconData(0xE9D0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData login_outline =
      IconData(0xE9D1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData logout_filled_1 =
      IconData(0xE9D2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData logout_filled =
      IconData(0xE9D3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData logout_outline_1 =
      IconData(0xE9D4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData logout_outline =
      IconData(0xE9D5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData map_location_filled =
      IconData(0xE9D6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData map_location_outline =
      IconData(0xE9D7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData medkit_filled =
      IconData(0xE9D8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData medkit_outline =
      IconData(0xE9D9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData menu =
      IconData(0xE9DA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData microscope =
      IconData(0xE9DB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData moon_filled =
      IconData(0xE9DC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData moon_outline =
      IconData(0xE9DD, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData more_horizontal_dot =
      IconData(0xE9DE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData more_vertical_dot =
      IconData(0xE9DF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData move_outline =
      IconData(0xE9E0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData navigation_filled =
      IconData(0xE9E1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData navigation_outline =
      IconData(0xE9E2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_filled =
      IconData(0xE9E3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_off_filled =
      IconData(0xE9E4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_off_outline =
      IconData(0xE9E5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_on_filled =
      IconData(0xE9E6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_on_outline =
      IconData(0xE9E7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_outline =
      IconData(0xE9E8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_10 =
      IconData(0xE9E9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_12 =
      IconData(0xE9EA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_13 =
      IconData(0xE9EB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_16 =
      IconData(0xE9EC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_17 =
      IconData(0xE9ED, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_18 =
      IconData(0xE9EE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_21 =
      IconData(0xE9EF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData paint_outline =
      IconData(0xE9F0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData palette_filled =
      IconData(0xE9F1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData pin_filled =
      IconData(0xE9F2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData pin_outline =
      IconData(0xE9F3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData plus_outline =
      IconData(0xE9F4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData power_button_filled =
      IconData(0xE9F5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData power_button_outline =
      IconData(0xE9F6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData pulse_filled =
      IconData(0xE9F7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData pulse_outline =
      IconData(0xE9F8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData refresh =
      IconData(0xE9F9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData rotate_360 =
      IconData(0xE9FA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData rows_filled =
      IconData(0xE9FB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData rows_outline =
      IconData(0xE9FC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData sand_watch_filled =
      IconData(0xE9FD, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData sand_watch_outline =
      IconData(0xE9FE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData save_filled =
      IconData(0xE9FF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData save_outline =
      IconData(0xEA00, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData search_outline =
      IconData(0xEA01, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData settings_cube_filled =
      IconData(0xEA02, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData setting_cube_outline =
      IconData(0xEA03, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData setting_star_filled =
      IconData(0xEA04, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData setting_star_outline =
      IconData(0xEA05, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shield_filled =
      IconData(0xEA06, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shield_outline =
      IconData(0xEA07, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_bag_filled =
      IconData(0xEA08, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_bag_outline =
      IconData(0xEA09, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_basket_filled =
      IconData(0xEA0A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_basket_outline =
      IconData(0xEA0B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_cart_filled =
      IconData(0xEA0C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_cart_outline =
      IconData(0xEA0D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData sort =
      IconData(0xEA0E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData speedometer_filled =
      IconData(0xEA0F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData speedometer_full_outline =
      IconData(0xEA10, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData speedometer_half =
      IconData(0xEA11, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData stack_filled =
      IconData(0xEA12, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData stack_outline =
      IconData(0xEA13, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_filled =
      IconData(0xEA14, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_half_left_filled =
      IconData(0xEA15, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_half_left_outline =
      IconData(0xEA16, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_half_right_filled =
      IconData(0xEA17, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_half_right_outline =
      IconData(0xEA18, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_outline =
      IconData(0xEA19, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData sun_filled =
      IconData(0xEA1A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData sun_outline =
      IconData(0xEA1B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData timer_filled =
      IconData(0xEA1C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData timer_outline =
      IconData(0xEA1D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData toggle_left_filled =
      IconData(0xEA1E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData toggle_left_outline =
      IconData(0xEA1F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData toggle_right_filled =
      IconData(0xEA20, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData toggle_right_outline =
      IconData(0xEA21, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData traffic_signal_filled =
      IconData(0xEA22, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData traffic_signal_outline =
      IconData(0xEA23, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData umbrella_filled =
      IconData(0xEA24, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData umbrella_outline =
      IconData(0xEA25, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData ungroup =
      IconData(0xEA26, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData university_filled =
      IconData(0xEA27, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData university_outline =
      IconData(0xEA28, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData unlock_filled =
      IconData(0xEA29, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData unlock_outline =
      IconData(0xEA2A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData upload_01_filled =
      IconData(0xEA2B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData upload_01_outline =
      IconData(0xEA2C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData upload_filled =
      IconData(0xEA2D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData upload_outline =
      IconData(0xEA2E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wallet_filled =
      IconData(0xEA2F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wallet_outline =
      IconData(0xEA30, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wifi =
      IconData(0xEA31, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wifi_filled =
      IconData(0xEA32, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wifi_off_outline =
      IconData(0xEA33, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wifi_on_outline =
      IconData(0xEA34, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData zoom_in_filled =
      IconData(0xEA35, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData zoom_in_outline =
      IconData(0xEA36, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData zoom_out_filled =
      IconData(0xEA37, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData zoom_out_outline =
      IconData(0xEA38, fontFamily: 'General', fontPackage: _fontPackage);
  // Brand________________________________________________________________________________
  static const IconData adobe_after_effects_filled =
      IconData(0xE900, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_after_effects_outline =
      IconData(0xE901, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_experince_design_filled =
      IconData(0xE902, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_experince_design_outline =
      IconData(0xE903, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_illustrator_filled =
      IconData(0xE904, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_illustrator_outline =
      IconData(0xE905, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_indesign_filled =
      IconData(0xE906, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_In_filled =
      IconData(0xE907, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_indesign_outline =
      IconData(0xE908, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_In_outline =
      IconData(0xE909, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_lightroom_filled =
      IconData(0xE90A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_lightroom_outline =
      IconData(0xE90B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_photoshop_filled =
      IconData(0xE90C, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_photoshop_outline =
      IconData(0xE90D, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_premiere_filled =
      IconData(0xE90E, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_premiere_outline =
      IconData(0xE90F, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData amazon_filled =
      IconData(0xE910, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData amazon_outline =
      IconData(0xE911, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData android_filled =
      IconData(0xE912, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData android_outline =
      IconData(0xE913, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData apple_filled =
      IconData(0xE914, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData apple_outline =
      IconData(0xE915, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData app_store_filled =
      IconData(0xE916, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData app_store_outline =
      IconData(0xE917, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData bitcoin_filled =
      IconData(0xE918, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData bitcoin_outline =
      IconData(0xE919, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData chrome_filled =
      IconData(0xE91A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData chrome_outline =
      IconData(0xE91B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData dribbble_filled =
      IconData(0xE91C, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData dribbble_outline =
      IconData(0xE91D, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData dropbox_filled =
      IconData(0xE91E, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData dropbox_outline =
      IconData(0xE91F, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData facebook_filled =
      IconData(0xE920, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData facebook_messenger_filled =
      IconData(0xE921, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData facebook_messenger_outline =
      IconData(0xE922, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData facebook_outline =
      IconData(0xE923, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData figma_filled =
      IconData(0xE924, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData figma_outline =
      IconData(0xE925, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData github_filled =
      IconData(0xE926, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData github_outline =
      IconData(0xE927, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData gmail_filled =
      IconData(0xE928, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData gmail_outline =
      IconData(0xE929, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_alt_filled =
      IconData(0xE92A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_alt_outline =
      IconData(0xE92B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_drive_filled =
      IconData(0xE92C, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_drive_outline =
      IconData(0xE92D, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_filled =
      IconData(0xE92E, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_outline =
      IconData(0xE92F, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_play_filled =
      IconData(0xE930, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_play_outline =
      IconData(0xE931, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData html_filled =
      IconData(0xE932, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData html_outline =
      IconData(0xE933, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData instagram_filled =
      IconData(0xE934, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData instagram_outline =
      IconData(0xE935, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData java_filled =
      IconData(0xE936, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData java_outline =
      IconData(0xE937, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData linkedin_filled =
      IconData(0xE938, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData linkedin_outline =
      IconData(0xE939, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData multi_chat_outline =
      IconData(0xE93A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData pinterest_filled =
      IconData(0xE93B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData pinterest_outline =
      IconData(0xE93C, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData qq_filled =
      IconData(0xE93D, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData qq_outline =
      IconData(0xE93E, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData react_outline =
      IconData(0xE93F, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData reddit_filled =
      IconData(0xE940, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData reddit_outline =
      IconData(0xE941, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData sketch_filled =
      IconData(0xE942, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData sketch_outline =
      IconData(0xE943, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData skype_filled =
      IconData(0xE944, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData skype_outline =
      IconData(0xE945, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData slack_filled =
      IconData(0xE946, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData slack_outline =
      IconData(0xE947, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData snapchat_filled =
      IconData(0xE948, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData snapchat_outline =
      IconData(0xE949, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData telegram_filled =
      IconData(0xE94A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData telegram_outline =
      IconData(0xE94B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData tumblr_filled =
      IconData(0xE94C, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData tumblr_outline =
      IconData(0xE94D, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData twitch_filled =
      IconData(0xE94E, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData twitch_outline =
      IconData(0xE94F, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData twitter_filled =
      IconData(0xE950, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData twitter_outline =
      IconData(0xE951, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData viber_filled =
      IconData(0xE952, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData viber_outline =
      IconData(0xE953, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData visual_filled =
      IconData(0xE954, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData visual_outline =
      IconData(0xE955, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData vk_filled =
      IconData(0xE956, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData vk_outline =
      IconData(0xE957, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData wechat_filled =
      IconData(0xE958, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData whatsapp_filled =
      IconData(0xE959, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData whatsapp_outline =
      IconData(0xE95A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData youtube_filled =
      IconData(0xE95B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData youtube_outline =
      IconData(0xE95C, fontFamily: 'Brand', fontPackage: _fontPackage);
  // Communication________________________________________________________________________________
  static const IconData chat_conversation_left_filled =
      IconData(0xE900, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_conversation_left_outline =
      IconData(0xE901, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_conversation_right_outline =
      IconData(0xE902, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_conversation__right_filled =
      IconData(0xE903, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_left_filled =
      IconData(0xE904, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_left_outline =
      IconData(0xE905, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_right_filled =
      IconData(0xE906, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_right_outline =
      IconData(0xE907, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_add_circle_outline =
      IconData(0xE908, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_add_filled =
      IconData(0xE909, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_block_circle_outline =
      IconData(0xE90A, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_block_filled =
      IconData(0xE90B, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_circle_outline =
      IconData(0xE90C, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_filled =
      IconData(0xE90D, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_on_circle_outline =
      IconData(0xE90E, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_on_filled =
      IconData(0xE90F, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_remove_circle_outline =
      IconData(0xE910, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_remove_filled =
      IconData(0xE911, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData contacts_filled =
      IconData(0xE912, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData contacts_outline =
      IconData(0xE913, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData dislike_filled =
      IconData(0xE914, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData dislike_outline =
      IconData(0xE915, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData forward_filled =
      IconData(0xE916, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData forward_outline =
      IconData(0xE917, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData like_filled =
      IconData(0xE918, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData like_outline =
      IconData(0xE919, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData message_filled =
      IconData(0xE91A, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData message_open_filled =
      IconData(0xE91B, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData message_open_outline =
      IconData(0xE91C, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData message_outline =
      IconData(0xE91D, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_filled =
      IconData(0xE91E, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_in_filled =
      IconData(0xE91F, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_in_outline =
      IconData(0xE920, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_miss_filled =
      IconData(0xE921, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_miss_outline =
      IconData(0xE922, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_off_filled =
      IconData(0xE923, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_off_outline =
      IconData(0xE924, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_outline =
      IconData(0xE925, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_out_filled =
      IconData(0xE926, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_out_outline =
      IconData(0xE927, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData reply_filled =
      IconData(0xE928, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData reply_outline =
      IconData(0xE929, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData send_filled =
      IconData(0xE92A, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData send_outline =
      IconData(0xE92B, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData share_box_filled =
      IconData(0xE92C, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData share_box_outline =
      IconData(0xE92D, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData share_filled =
      IconData(0xE92E, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData share_outline =
      IconData(0xE92F, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData sound_high_filled =
      IconData(0xE930, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData sound_high_outline =
      IconData(0xE931, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData sound_low_filled =
      IconData(0xE932, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData sound_low_outline =
      IconData(0xE933, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_add_outline =
      IconData(0xE934, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_block_filled =
      IconData(0xE935, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_block_outline =
      IconData(0xE936, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_clock_filled =
      IconData(0xE937, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_clock_outline =
      IconData(0xE938, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_filled_1 =
      IconData(0xE939, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_filled =
      IconData(0xE93A, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_outline =
      IconData(0xE93B, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_plus_filled =
      IconData(0xE93C, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_range_outline =
      IconData(0xE93D, fontFamily: 'Communication', fontPackage: _fontPackage);
// Media________________________________________________________________________________
  static const IconData fast_forward_filled =
      IconData(0xE900, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData fast_forward_outline =
      IconData(0xE901, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData fast_rewind_filled =
      IconData(0xE902, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData fast_rewind_outline =
      IconData(0xE903, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData headphone_filled =
      IconData(0xE904, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData headphone_outline =
      IconData(0xE905, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData headset_filled =
      IconData(0xE906, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData headset_outline =
      IconData(0xE907, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData microphone_filled =
      IconData(0xE908, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData microphone_off_filled =
      IconData(0xE909, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData microphone_off_outline =
      IconData(0xE90A, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData microphone_outline =
      IconData(0xE90B, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_add_filled =
      IconData(0xE90C, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_add_outline =
      IconData(0xE90D, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_album_filled =
      IconData(0xE90E, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_album_outline =
      IconData(0xE90F, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_cut_filled =
      IconData(0xE910, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_cut_outline =
      IconData(0xE911, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_filled =
      IconData(0xE912, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_outline =
      IconData(0xE913, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_pause_filled =
      IconData(0xE914, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_pause_outline =
      IconData(0xE915, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_paylist_filled =
      IconData(0xE916, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_playlist_outline =
      IconData(0xE917, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_play_filled =
      IconData(0xE918, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_play_outline =
      IconData(0xE919, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_remove_filled =
      IconData(0xE91A, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_remove_outline =
      IconData(0xE91B, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_stop_filled =
      IconData(0xE91C, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_stop_outline =
      IconData(0xE91D, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData pause_filled =
      IconData(0xE91E, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData pause_outline =
      IconData(0xE91F, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData play_filled =
      IconData(0xE920, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData play_outline =
      IconData(0xE921, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData play_switch_filled =
      IconData(0xE922, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData play_switch_outline =
      IconData(0xE923, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData shuffle_filled =
      IconData(0xE924, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData shuffle_outline =
      IconData(0xE925, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData skip_next_filled =
      IconData(0xE926, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData skip_next_outline =
      IconData(0xE927, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData skip_prev_filled =
      IconData(0xE928, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData skip_prev_outline =
      IconData(0xE929, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData stop_filled =
      IconData(0xE92A, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData stop_outline =
      IconData(0xE92B, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_down_filled =
      IconData(0xE92C, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_down_outline =
      IconData(0xE92D, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_off_filled =
      IconData(0xE92E, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_off_outline =
      IconData(0xE92F, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_up_filled =
      IconData(0xE930, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_up_outline =
      IconData(0xE931, fontFamily: 'Media', fontPackage: _fontPackage);
// Other________________________________________________________________________________
  static const IconData battery_empty_filled =
      IconData(0xE900, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_empty_outline =
      IconData(0xE901, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_full_filled =
      IconData(0xE902, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_full_outline =
      IconData(0xE903, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_low_filled =
      IconData(0xE904, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_low_outline =
      IconData(0xE905, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_most_filled =
      IconData(0xE906, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_most_outline =
      IconData(0xE907, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_quarter_filled =
      IconData(0xE908, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_quarter_outline =
      IconData(0xE909, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battry_half_filled =
      IconData(0xE90A, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battry_half_outline =
      IconData(0xE90B, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData binocular_filled =
      IconData(0xE90C, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData binocular_outline =
      IconData(0xE90D, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData camera_filled =
      IconData(0xE90E, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData camera_outline =
      IconData(0xE90F, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData desktop_filled =
      IconData(0xE910, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData desktop_outline =
      IconData(0xE911, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData dialpad_filled =
      IconData(0xE912, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData dialpad_outline =
      IconData(0xE913, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData gamepad_filled =
      IconData(0xE914, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData gamepad_outline =
      IconData(0xE915, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mobile_phone_filled =
      IconData(0xE916, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mobile_phone_outline =
      IconData(0xE917, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mouse_alt_filled =
      IconData(0xE918, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mouse_alt_outline =
      IconData(0xE919, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mouse_filled =
      IconData(0xE91A, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mouse_outline =
      IconData(0xE91B, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData printer_filled =
      IconData(0xE91C, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData printer_outline =
      IconData(0xE91D, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData processor_filled =
      IconData(0xE91E, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData processor_outline =
      IconData(0xE91F, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData server_filled =
      IconData(0xE920, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData server_outline =
      IconData(0xE921, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData video_camera_filled =
      IconData(0xE922, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData video_camera_outline =
      IconData(0xE923, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData watch_filled =
      IconData(0xE924, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData watch_outline =
      IconData(0xE925, fontFamily: 'Other', fontPackage: _fontPackage);
}
