library ico;

import 'package:flutter/material.dart';

/// Return IconData
class Ico {
  // This class is not meant to be instantiated or extended; this constructor
  // prevents instantiation and extension.
  static const _fontPackage = 'ico';
  Ico._();
// General Icons__________________________________________________________
  static const IconData num_10 =
      IconData(0x0029, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_12 =
      IconData(0x002A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_13 =
      IconData(0x002B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_16 =
      IconData(0x002C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_17 =
      IconData(0x002D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_18 =
      IconData(0x002E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData num_21 =
      IconData(0x002F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData rotate_360 =
      IconData(0x0030, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData add_filled =
      IconData(0x0031, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData add_outline =
      IconData(0x0032, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData adjust_filled =
      IconData(0x0033, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData adjust_outline =
      IconData(0x0034, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData alarm_filled =
      IconData(0x0035, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData alarm_outline =
      IconData(0x0036, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData apps_filled =
      IconData(0x0037, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData apps_outline =
      IconData(0x0038, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_down =
      IconData(0x0039, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_down_01 =
      IconData(0x003A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_left =
      IconData(0x003B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_left_01 =
      IconData(0x003C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_right =
      IconData(0x003D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_right_01 =
      IconData(0x003E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_up =
      IconData(0x003F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData arrow_up_01 =
      IconData(0x0040, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData attach =
      IconData(0x0041, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData at_sign =
      IconData(0x0042, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData at_sign_filled =
      IconData(0x0043, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData award_filled =
      IconData(0x0044, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData award_outline =
      IconData(0x0045, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData backspace_filled =
      IconData(0x0046, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData backspace_outline =
      IconData(0x0047, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bag_filled =
      IconData(0x0048, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bag_outline =
      IconData(0x0049, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bank_filled =
      IconData(0x004A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bank_outline =
      IconData(0x004B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData beakers_circle_filled =
      IconData(0x004C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData beakers_circle_outline =
      IconData(0x004D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData beakers_triangle_filled =
      IconData(0x004E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData beakers_triangle_outline =
      IconData(0x004F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bluetooth_outline =
      IconData(0x0050, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bookmark_filled =
      IconData(0x0051, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData bookmark_outline =
      IconData(0x0052, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_check_filled =
      IconData(0x0053, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_check_outline =
      IconData(0x0054, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_filled =
      IconData(0x0055, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_mark_filled =
      IconData(0x0056, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_mark_outline =
      IconData(0x0057, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_open_filled =
      IconData(0x0058, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_open_outline =
      IconData(0x0059, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData book_outline =
      IconData(0x005A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData box_filled =
      IconData(0x005B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData box_outline =
      IconData(0x005C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData calendar_filled =
      IconData(0x005D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData calendar_outline =
      IconData(0x005E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cancel_filled =
      IconData(0x005F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cancel_outline =
      IconData(0x0060, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData card_filled =
      IconData(0x0061, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData card_outline =
      IconData(0x0062, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData_alt_filled =
      IconData(0x0063, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData_alt_outline =
      IconData(0x0064, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData chart_pie_filled =
      IconData(0x0065, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData chart_pie_outline =
      IconData(0x0066, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData check =
      IconData(0x0067, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData checked_box_filled =
      IconData(0x0068, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData checked_box_outline =
      IconData(0x0069, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clipboard_alt_filled =
      IconData(0x006A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clipboard_alt_outline =
      IconData(0x006B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clipboard_filled =
      IconData(0x006C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clipboard_outline =
      IconData(0x006D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clock_filled =
      IconData(0x006E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData clock_outline =
      IconData(0x006F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_check_filled =
      IconData(0x0070, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_check_outline =
      IconData(0x0071, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_download_filled =
      IconData(0x0072, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_download_outline =
      IconData(0x0073, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_filled =
      IconData(0x0074, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_off_filled =
      IconData(0x0075, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_off_outline =
      IconData(0x0076, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_outline =
      IconData(0x0077, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_upload_filled =
      IconData(0x0078, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cloud_upload_outline =
      IconData(0x0079, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData collapse =
      IconData(0x007A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData columns_filled =
      IconData(0x007B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData columns_outline =
      IconData(0x007C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData copy_filled =
      IconData(0x007D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData copy_outline =
      IconData(0x007E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cross_outline =
      IconData(0x007F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData current_location_filled =
      IconData(0x0080, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData current_location_outline =
      IconData(0x0081, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cursor_filled =
      IconData(0x0082, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData cursor_outline =
      IconData(0x0083, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData delete_filled =
      IconData(0x0084, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData delete_forever_filled =
      IconData(0x0085, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData delete_forever_outline =
      IconData(0x0086, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData delete_outline =
      IconData(0x0087, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData diamond_filled =
      IconData(0x0088, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData diamond_outline =
      IconData(0x0089, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData download_01_filled =
      IconData(0x008A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData download_01_outline =
      IconData(0x008B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData download_filled =
      IconData(0x008C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData download_outline =
      IconData(0x008D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData edit_alt_filled =
      IconData(0x008E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData edit_alt_outline =
      IconData(0x008F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData edit_filled =
      IconData(0x0090, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData edit_outline =
      IconData(0x0091, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData exchange =
      IconData(0x0092, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData expand =
      IconData(0x0093, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData explore_filled =
      IconData(0x0094, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData explore_outline =
      IconData(0x0095, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData eye_closed_filled =
      IconData(0x0096, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData eye_closed_outline =
      IconData(0x0097, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData eye_filled =
      IconData(0x0098, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData eye_outline =
      IconData(0x0099, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_add_filled =
      IconData(0x009A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_add_outline =
      IconData(0x009B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_download_filled =
      IconData(0x009C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_download_outline =
      IconData(0x009D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_empty_filled =
      IconData(0x009E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_empty_outline =
      IconData(0x009F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_favourite_filled =
      IconData(0x00A0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_favourite_outline =
      IconData(0x00A1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_filled =
      IconData(0x00A2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_ftp_filled =
      IconData(0x00A3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_ftp_outline =
      IconData(0x00A4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_image_filled =
      IconData(0x00A5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_image_outline =
      IconData(0x00A6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_invalid_filled =
      IconData(0x00A7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_invalid_outline =
      IconData(0x00A8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_outline =
      IconData(0x00A9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_remove_filled =
      IconData(0x00AA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_remove_outline =
      IconData(0x00AB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_unknown_filled =
      IconData(0x00AC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_unknown_outline =
      IconData(0x00AD, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_upload_filled =
      IconData(0x00AE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_upload_outline =
      IconData(0x00AF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_user_filled =
      IconData(0x00B0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData file_user_outline =
      IconData(0x00B1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData filter_filled =
      IconData(0x00B2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData filter_outline =
      IconData(0x00B3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData fire_filled =
      IconData(0x00B4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData fire_outline =
      IconData(0x00B5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_add_filled =
      IconData(0x00B6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_add_outline =
      IconData(0x00B7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_block_filled =
      IconData(0x00B8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_block_outline =
      IconData(0x00B9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_delete_filled =
      IconData(0x00BA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_delete_outline =
      IconData(0x00BB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_filled =
      IconData(0x00BC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_ftp_filled =
      IconData(0x00BD, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_ftp_outline =
      IconData(0x00BE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_lock_filled =
      IconData(0x00BF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_lock_outline =
      IconData(0x00C0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_open_filled =
      IconData(0x00C1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_open_outline =
      IconData(0x00C2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_outline =
      IconData(0x00C3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_search_filled =
      IconData(0x00C4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_search_outline =
      IconData(0x00C5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_user_filled =
      IconData(0x00C6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData folder_user_outline =
      IconData(0x00C7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData gift_filled =
      IconData(0x00C8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData gift_outline =
      IconData(0x00C9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData globe_filled =
      IconData(0x00CA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData globe_outline =
      IconData(0x00CB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData group =
      IconData(0x00CC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heartbeat_filled =
      IconData(0x00CD, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heartbeat_outline =
      IconData(0x00CE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_add_filled =
      IconData(0x00CF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_add_outline =
      IconData(0x00D0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_filled =
      IconData(0x00D1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_off_filled =
      IconData(0x00D2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_off_outline =
      IconData(0x00D3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_outline =
      IconData(0x00D4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_remove_filled =
      IconData(0x00D5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData heart_remove_outline =
      IconData(0x00D6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData history_outline =
      IconData(0x00D7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData home_filled =
      IconData(0x00D8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData home_outline =
      IconData(0x00D9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData hotspot =
      IconData(0x00DA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData image_filled =
      IconData(0x00DB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData image_outline =
      IconData(0x00DC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_circle_filled =
      IconData(0x00DD, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_circle_outline =
      IconData(0x00DE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_rect_filled =
      IconData(0x00DF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_rect_outline =
      IconData(0x00E0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_triangle_filled =
      IconData(0x00E1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData info_triangle_outline =
      IconData(0x00E2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData invoice_filled =
      IconData(0x00E3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData invoice_outline =
      IconData(0x00E4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData key_filled =
      IconData(0x00E5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData key_outline =
      IconData(0x00E6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData layout_filled =
      IconData(0x00E7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData layout_outline =
      IconData(0x00E8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_alt_filled =
      IconData(0x00E9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_alt_outline =
      IconData(0x00EA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_filled =
      IconData(0x00EB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_off_filled =
      IconData(0x00EC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_off_outline =
      IconData(0x00ED, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightbulb_outline =
      IconData(0x00EE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightning_alt_filled =
      IconData(0x00EF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightning_alt_outline =
      IconData(0x00F0, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightning_filled =
      IconData(0x00F1, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lightning_outline =
      IconData(0x00F2, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_add_outline =
      IconData(0x00F3, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_check_filled =
      IconData(0x00F4, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_check_outline =
      IconData(0x00F5, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_filled =
      IconData(0x00F6, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_outline =
      IconData(0x00F7, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_plus_filled =
      IconData(0x00F8, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_question_filled =
      IconData(0x00F9, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData location_question_outline =
      IconData(0x00FA, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lock_filled =
      IconData(0x00FB, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lock_outline =
      IconData(0x00FC, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lock_time_filled =
      IconData(0x00FD, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData lock_time_outline =
      IconData(0x00FE, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData login_filled_01 =
      IconData(0x00FF, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData login_filled =
      IconData(0x0100, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData login_outline_01 =
      IconData(0x0101, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData login_outline =
      IconData(0x0102, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData logout_filled_01 =
      IconData(0x0103, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData logout_filled =
      IconData(0x0104, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData logout_outline_01 =
      IconData(0x0105, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData logout_outline =
      IconData(0x0106, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData map_location_filled =
      IconData(0x0107, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData map_location_outline =
      IconData(0x0108, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData medkit_filled =
      IconData(0x0109, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData medkit_outline =
      IconData(0x010A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData menu =
      IconData(0x010B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData microscope =
      IconData(0x010C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData moon_filled =
      IconData(0x010D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData moon_outline =
      IconData(0x010E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData more_horizontal_dot =
      IconData(0x010F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData more_vertical_dot =
      IconData(0x0110, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData move_outline =
      IconData(0x0111, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData navigation_filled =
      IconData(0x0112, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData navigation_outline =
      IconData(0x0113, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_filled =
      IconData(0x0114, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_off_filled =
      IconData(0x0115, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_off_outline =
      IconData(0x0116, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_on_filled =
      IconData(0x0117, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_on_outline =
      IconData(0x0118, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData notification_outline =
      IconData(0x0119, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData paint_outline =
      IconData(0x011A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData palette_filled =
      IconData(0x011B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData pin_filled =
      IconData(0x011C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData pin_outline =
      IconData(0x011D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData plus_outline =
      IconData(0x011E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData power_button_filled =
      IconData(0x011F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData power_button_outline =
      IconData(0x0120, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData pulse_filled =
      IconData(0x0121, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData pulse_outline =
      IconData(0x0122, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData refresh =
      IconData(0x0123, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData rows_filled =
      IconData(0x0124, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData rows_outline =
      IconData(0x0125, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData sand_watch_filled =
      IconData(0x0126, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData sand_watch_outline =
      IconData(0x0127, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData save_filled =
      IconData(0x0128, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData save_outline =
      IconData(0x0129, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData search_outline =
      IconData(0x012A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData settings_cube_filled =
      IconData(0x012B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData setting_cube_outline =
      IconData(0x012C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData setting_star_filled =
      IconData(0x012D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData setting_star_outline =
      IconData(0x012E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shield_filled =
      IconData(0x012F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shield_outline =
      IconData(0x0130, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_bag_filled =
      IconData(0x0131, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_bag_outline =
      IconData(0x0132, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_basket_filled =
      IconData(0x0133, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_basket_outline =
      IconData(0x0134, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_cart_filled =
      IconData(0x0135, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData shopping_cart_outline =
      IconData(0x0136, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData sort =
      IconData(0x0137, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData speedometer_filled =
      IconData(0x0138, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData speedometer_full_outline =
      IconData(0x0139, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData speedometer_half =
      IconData(0x013A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData stack_filled =
      IconData(0x013B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData stack_outline =
      IconData(0x013C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_filled =
      IconData(0x013D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_half_left_filled =
      IconData(0x013E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_half_left_outline =
      IconData(0x013F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_half_right_filled =
      IconData(0x0140, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_half_right_outline =
      IconData(0x0141, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData star_outline =
      IconData(0x0142, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData sun_filled =
      IconData(0x0143, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData sun_outline =
      IconData(0x0144, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData timer_filled =
      IconData(0x0145, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData timer_outline =
      IconData(0x0146, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData toggle_left_filled =
      IconData(0x0147, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData toggle_left_outline =
      IconData(0x0148, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData toggle_right_filled =
      IconData(0x0149, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData toggle_right_outline =
      IconData(0x014A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData traffic_signal_filled =
      IconData(0x014B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData traffic_signal_outline =
      IconData(0x014C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData umbrella_filled =
      IconData(0x014D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData umbrella_outline =
      IconData(0x014E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData ungroup =
      IconData(0x014F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData university_filled =
      IconData(0x0150, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData university_outline =
      IconData(0x0151, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData unlock_filled =
      IconData(0x0152, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData unlock_outline =
      IconData(0x0153, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData upload_01_filled =
      IconData(0x0154, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData upload_01_outline =
      IconData(0x0155, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData upload_filled =
      IconData(0x0156, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData upload_outline =
      IconData(0x0157, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wallet_filled =
      IconData(0x0158, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wallet_outline =
      IconData(0x0159, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wifi =
      IconData(0x015A, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wifi_filled =
      IconData(0x015B, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wifi_off_outline =
      IconData(0x015C, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData wifi_on_outline =
      IconData(0x015D, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData zoom_in_filled =
      IconData(0x015E, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData zoom_in_outline =
      IconData(0x015F, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData zoom_out_filled =
      IconData(0x0160, fontFamily: 'General', fontPackage: _fontPackage);
  static const IconData zoom_out_outline =
      IconData(0x0161, fontFamily: 'General', fontPackage: _fontPackage);

  // Brand________________________________________________________________________________
  static const IconData adobe_after_effects_filled =
      IconData(0x0000, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_after_effects_outline =
      IconData(0x0001, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_experince_design_filled =
      IconData(0x0002, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_experince_design_outline =
      IconData(0x0003, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_illustrator_filled =
      IconData(0x0004, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_illustrator_outline =
      IconData(0x0005, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_indesign_filled_1 =
      IconData(0x0006, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_indesign_filled =
      IconData(0x0007, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_indesign_outline_1 =
      IconData(0x0008, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_indesign_outline =
      IconData(0x0009, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_lightroom_filled =
      IconData(0x000A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_lightroom_outline =
      IconData(0x000B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_photoshop_filled =
      IconData(0x000C, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_photoshop_outline =
      IconData(0x000D, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_premiere_filled =
      IconData(0x000E, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData adobe_premiere_outline =
      IconData(0x000F, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData amazon_filled =
      IconData(0x0010, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData amazon_outline =
      IconData(0x0011, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData android_filled =
      IconData(0x0012, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData android_outline =
      IconData(0x0013, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData apple_filled =
      IconData(0x0014, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData apple_outline =
      IconData(0x0015, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData app_store_filled =
      IconData(0x0016, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData app_store_outline =
      IconData(0x0017, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData bitcoin_filled =
      IconData(0x0018, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData bitcoin_outline =
      IconData(0x0019, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData chrome_filled =
      IconData(0x001A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData chrome_outline =
      IconData(0x001B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData dribbble_filled =
      IconData(0x001C, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData dribbble_outline =
      IconData(0x001D, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData dropbox_filled =
      IconData(0x001E, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData dropbox_outline =
      IconData(0x001F, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData facebook_filled =
      IconData(0x0020, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData facebook_messenger_filled =
      IconData(0x0021, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData facebook_messenger_outline =
      IconData(0x0022, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData facebook_outline =
      IconData(0x0023, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData figma_filled =
      IconData(0x0024, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData figma_outline =
      IconData(0x0025, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData github_filled =
      IconData(0x0026, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData github_outline =
      IconData(0x0027, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData gmail_filled =
      IconData(0x0028, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData gmail_outline =
      IconData(0x0029, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_alt_filled =
      IconData(0x002A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_alt_outline =
      IconData(0x002B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_drive_filled =
      IconData(0x002C, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_drive_outline =
      IconData(0x002D, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_filled =
      IconData(0x002E, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_outline =
      IconData(0x002F, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_play_filled =
      IconData(0x0030, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData google_play_outline =
      IconData(0x0031, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData html_filled =
      IconData(0x0032, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData html_outline =
      IconData(0x0033, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData instagram_filled =
      IconData(0x0034, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData instagram_outline =
      IconData(0x0035, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData java_filled =
      IconData(0x0036, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData java_outline =
      IconData(0x0037, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData linkedin_filled =
      IconData(0x0038, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData linkedin_outline =
      IconData(0x0039, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData multi_chat_outline =
      IconData(0x003A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData pinterest_filled =
      IconData(0x003B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData pinterest_outline =
      IconData(0x003C, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData qq_filled =
      IconData(0x003D, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData qq_outline =
      IconData(0x003E, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData react_outline =
      IconData(0x003F, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData reddit_filled =
      IconData(0x0040, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData reddit_outline =
      IconData(0x0041, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData sketch_filled =
      IconData(0x0042, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData sketch_outline =
      IconData(0x0043, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData skype_filled =
      IconData(0x0044, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData skype_outline =
      IconData(0x0045, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData slack_filled =
      IconData(0x0046, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData slack_outline =
      IconData(0x0047, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData snapchat_filled =
      IconData(0x0048, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData snapchat_outline =
      IconData(0x0049, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData telegram_filled =
      IconData(0x004A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData telegram_outline =
      IconData(0x004B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData tumblr_filled =
      IconData(0x004C, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData tumblr_outline =
      IconData(0x004D, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData twitch_filled =
      IconData(0x004E, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData twitch_outline =
      IconData(0x004F, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData twitter_filled =
      IconData(0x0050, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData twitter_outline =
      IconData(0x0051, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData viber_filled =
      IconData(0x0052, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData viber_outline =
      IconData(0x0053, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData visual_filled =
      IconData(0x0054, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData visual_outline =
      IconData(0x0055, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData vk_filled =
      IconData(0x0056, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData vk_outline =
      IconData(0x0057, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData wechat_filled =
      IconData(0x0058, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData whatsapp_filled =
      IconData(0x0059, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData whatsapp_outline =
      IconData(0x005A, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData youtube_filled =
      IconData(0x005B, fontFamily: 'Brand', fontPackage: _fontPackage);
  static const IconData youtube_outline =
      IconData(0x005C, fontFamily: 'Brand', fontPackage: _fontPackage);

  // Communication________________________________________________________________________________
  static const IconData chat_conversation_left_filled =
      IconData(0x0000, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_conversation_left_outline =
      IconData(0x0001, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_conversation_right_outline =
      IconData(0x0002, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_conversation__right_filled =
      IconData(0x0003, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_left_filled =
      IconData(0x0004, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_left_outline =
      IconData(0x0005, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_right_filled =
      IconData(0x0006, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData chat_right_outline =
      IconData(0x0007, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_add_circle_outline =
      IconData(0x0008, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_add_filled =
      IconData(0x0009, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_block_circle_outline =
      IconData(0x000A, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_block_filled =
      IconData(0x000B, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_circle_outline =
      IconData(0x000C, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_filled =
      IconData(0x000D, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_on_circle_outline =
      IconData(0x000E, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_on_filled =
      IconData(0x000F, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_remove_circle_outline =
      IconData(0x0010, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData comment_remove_filled =
      IconData(0x0011, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData contacts_filled =
      IconData(0x0012, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData contacts_outline =
      IconData(0x0013, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData dislike_filled =
      IconData(0x0014, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData dislike_outline =
      IconData(0x0015, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData forward_filled =
      IconData(0x0016, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData forward_outline =
      IconData(0x0017, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData like_filled =
      IconData(0x0018, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData like_outline =
      IconData(0x0019, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData message_filled =
      IconData(0x001A, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData message_open_filled =
      IconData(0x001B, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData message_open_outline =
      IconData(0x001C, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData message_outline =
      IconData(0x001D, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_filled =
      IconData(0x001E, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_in_filled =
      IconData(0x001F, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_in_outline =
      IconData(0x0020, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_miss_filled =
      IconData(0x0021, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_miss_outline =
      IconData(0x0022, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_off_filled =
      IconData(0x0023, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_off_outline =
      IconData(0x0024, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_outline =
      IconData(0x0025, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_out_filled =
      IconData(0x0026, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData phone_out_outline =
      IconData(0x0027, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData reply_filled =
      IconData(0x0028, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData reply_outline =
      IconData(0x0029, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData send_filled =
      IconData(0x002A, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData send_outline =
      IconData(0x002B, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData share_box_filled =
      IconData(0x002C, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData share_box_outline =
      IconData(0x002D, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData share_filled =
      IconData(0x002E, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData share_outline =
      IconData(0x002F, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData sound_high_filled =
      IconData(0x0030, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData sound_high_outline =
      IconData(0x0031, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData sound_low_filled =
      IconData(0x0032, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData sound_low_outline =
      IconData(0x0033, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_add_outline =
      IconData(0x0034, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_block_filled =
      IconData(0x0035, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_block_outline =
      IconData(0x0036, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_clock_filled =
      IconData(0x0037, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_clock_outline =
      IconData(0x0038, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_filled_1 =
      IconData(0x0039, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_filled =
      IconData(0x003A, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_outline =
      IconData(0x003B, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_plus_filled =
      IconData(0x003C, fontFamily: 'Communication', fontPackage: _fontPackage);
  static const IconData user_range_outline =
      IconData(0x003D, fontFamily: 'Communication', fontPackage: _fontPackage);

// Media________________________________________________________________________________
  static const IconData fast_forward_filled =
      IconData(0x0000, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData fast_forward_outline =
      IconData(0x0001, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData fast_rewind_filled =
      IconData(0x0002, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData fast_rewind_outline =
      IconData(0x0003, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData headphone_filled =
      IconData(0x0004, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData headphone_outline =
      IconData(0x0005, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData headset_filled =
      IconData(0x0006, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData headset_outline =
      IconData(0x0007, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData microphone_filled =
      IconData(0x0008, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData microphone_off_filled =
      IconData(0x0009, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData microphone_off_outline =
      IconData(0x000A, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData microphone_outline =
      IconData(0x000B, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_add_filled =
      IconData(0x000C, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_add_outline =
      IconData(0x000D, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_album_filled =
      IconData(0x000E, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_album_outline =
      IconData(0x000F, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_cut_filled =
      IconData(0x0010, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_cut_outline =
      IconData(0x0011, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_filled =
      IconData(0x0012, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_outline =
      IconData(0x0013, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_pause_filled =
      IconData(0x0014, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_pause_outline =
      IconData(0x0015, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_paylist_filled =
      IconData(0x0016, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_playlist_outline =
      IconData(0x0017, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_play_filled =
      IconData(0x0018, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_play_outline =
      IconData(0x0019, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_remove_filled =
      IconData(0x001A, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_remove_outline =
      IconData(0x001B, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_stop_filled =
      IconData(0x001C, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData music_stop_outline =
      IconData(0x001D, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData pause_filled =
      IconData(0x001E, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData pause_outline =
      IconData(0x001F, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData play_filled =
      IconData(0x0020, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData play_outline =
      IconData(0x0021, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData play_switch_filled =
      IconData(0x0022, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData play_switch_outline =
      IconData(0x0023, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData shuffle =
      IconData(0x0024, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData shuffle_outline =
      IconData(0x0025, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData skip_next_filled =
      IconData(0x0026, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData skip_next_outline =
      IconData(0x0027, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData skip_prev_filled =
      IconData(0x0028, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData skip_prev_outline =
      IconData(0x0029, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData stop_filled =
      IconData(0x002A, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData stop_outline =
      IconData(0x002B, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_down_filled =
      IconData(0x002C, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_down_outline =
      IconData(0x002D, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_off_filled =
      IconData(0x002E, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_off_outline =
      IconData(0x002F, fontFamily: 'Media', fontPackage: _fontPackage);
  static const IconData volume_up_filled =
      IconData(0x0030, fontFamily: 'Media', fontPackage: _fontPackage);

// Other________________________________________________________________________________
  static const IconData battery_empty_filled =
      IconData(0x0000, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_empty_outline =
      IconData(0x0001, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_full_filled =
      IconData(0x0002, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_full_outline =
      IconData(0x0003, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_low_filled =
      IconData(0x0004, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_low_outline =
      IconData(0x0005, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_most_filled =
      IconData(0x0006, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_most_outline =
      IconData(0x0007, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_quarter_filled =
      IconData(0x0008, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battery_quarter_outline =
      IconData(0x0009, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battry_half_filled =
      IconData(0x000A, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData battry_half_outline =
      IconData(0x000B, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData binocular_filled =
      IconData(0x000C, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData binocular_outline =
      IconData(0x000D, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData camera_filled =
      IconData(0x000E, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData camera_outline =
      IconData(0x000F, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData desktop_filled =
      IconData(0x0010, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData desktop_outline =
      IconData(0x0011, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData dialpad_filled =
      IconData(0x0012, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData dialpad_outline =
      IconData(0x0013, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData gamepad_filled =
      IconData(0x0014, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData gamepad_outline =
      IconData(0x0015, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mobile_phone_filled =
      IconData(0x0016, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mobile_phone_outline =
      IconData(0x0017, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mouse_alt_filled =
      IconData(0x0018, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mouse_alt_outline =
      IconData(0x0019, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mouse_filled =
      IconData(0x001A, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData mouse_outline =
      IconData(0x001B, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData printer_filled =
      IconData(0x001C, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData printer_outline =
      IconData(0x001D, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData processor_filled =
      IconData(0x001E, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData processor_outline =
      IconData(0x001F, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData server_filled =
      IconData(0x0020, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData server_outline =
      IconData(0x0021, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData video_camera_filled =
      IconData(0x0022, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData video_camera_outline =
      IconData(0x0023, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData watch_filled =
      IconData(0x0024, fontFamily: 'Other', fontPackage: _fontPackage);
  static const IconData watch_outline =
      IconData(0x0025, fontFamily: 'Other', fontPackage: _fontPackage);
}
